id = "vesti"
name = "Vesti"
version = "0.0.1"
schema_version = 1
authors = ["Sungbae Jeong <almagest0328@gmail.com>"]
description = "vesti language extension for zed"
repository = ""

[grammars.vesti]
repository = "https://github.com/e0328eric/tree-sitter-vesti"
rev = "c98aac7a11071cd0a2adf61fc2dad5a4a3b2bd0b"
